import Foundation
import SwiftUI

// MARK: - 国际化服务
class LocalizationService: ObservableObject {
    static let shared = LocalizationService()

    @Published var currentLanguage: Language {
        didSet {
            UserDefaults.standard.set(currentLanguage.rawValue, forKey: "app_language")
        }
    }

    enum Language: String, CaseIterable {
        case english = "en"
        case chinese = "zh-Hans"
        case japanese = "ja"

        var displayName: String {
            switch self {
            case .english: return "English"
            case .chinese: return "中文"
            case .japanese: return "日本語"
            }
        }
    }

    private init() {
        // 检测系统语言
        let systemLanguage = Self.detectSystemLanguage()
        let saved = UserDefaults.standard.string(forKey: "app_language")

        if let saved = saved, let language = Language(rawValue: saved) {
            self.currentLanguage = language
        } else {
            // 使用系统语言或默认英语
            self.currentLanguage = systemLanguage
        }
    }

    private static func detectSystemLanguage() -> Language {
        let preferredLanguages = Locale.preferredLanguages

        for languageCode in preferredLanguages {
            let lowercased = languageCode.lowercased()

            // 检测中文
            if lowercased.hasPrefix("zh") {
                return .chinese
            }
            // 检测日文
            if lowercased.hasPrefix("ja") {
                return .japanese
            }
            // 检测英文
            if lowercased.hasPrefix("en") {
                return .english
            }
        }

        // 默认返回英语
        return .english
    }

    func setLanguage(_ language: Language) {
        withAnimation(.easeInOut(duration: 0.2)) {
            currentLanguage = language
        }
    }

    // 本地化字符串
    func t(_ key: String) -> String {
        translations[currentLanguage]?[key] ?? key
    }
}

// MARK: - 翻译字典
private let translations: [LocalizationService.Language: [String: String]] = [
    .english: [
        // Launch at Login
        "launchAtLogin": "LAUNCH AT LOGIN",
        "launchAtLoginDesc": "Automatically start WallHaven when you log in.",
        "launchAtLoginSubtitle": "Start minimized in menu bar, applying dynamic wallpapers automatically.",
        // Categories
        "category.general": "GENERAL",
        "category.anime": "ANIME",
        "category.people": "PEOPLE",
        "category.nature": "NATURE",
        "category.technology": "TECH",
        // UI
        "search.placeholder": "SEARCH...",
        "filters": "FILTERS",
        "reset.all": "RESET ALL",
        "apply.filters": "APPLY FILTERS",
        "cancel": "CANCEL",
        // Sections
        "featured": "FEATURED",
        "view.all": "VIEW ALL",
        "all.wallpapers": "ALL WALLPAPERS",
        "loading.more": "LOADING MORE...",
        "no.wallpapers": "NO WALLPAPERS FOUND",
        // Filter
        "categories": "CATEGORIES",
        "purity": "PURITY",
        "sorting": "SORTING",
        "resolutions": "RESOLUTIONS",
        "ratios": "RATIOS",
        "colors": "COLORS",
        "sfw": "SFW",
        "sketchy": "SKETCHY",
        "nsfw": "NSFW",
        "descending": "DESCENDING",
        "ascending": "ASCENDING",
        "top.range": "TOP RANGE:",
        "date": "DATE",
        "date.added": "DATE ADDED",
        "views": "VIEWS",
        "favorites": "FAVORITES",
        "toplist": "TOPLIST",
        "random": "RANDOM",
        "relevance": "RELEVANCE",
        "order": "ORDER",
        "general": "GENERAL",
        "anime": "ANIME",
        "people": "PEOPLE",
        "more.filters": "MORE",
        "clear": "CLEAR",
        // Colors
        "color.red": "RED",
        "color.green": "GREEN",
        "color.blue": "BLUE",
        "color.yellow": "YELLOW",
        "color.purple": "PURPLE",
        "color.teal": "TEAL",
        "color.orange": "ORANGE",
        "color.violet": "VIOLET",
        "color.skyblue": "SKY BLUE",
        "color.gray": "GRAY",
        "color.black": "BLACK",
        "color.white": "WHITE",
        // Actions
        "download.original": "DOWNLOAD ORIGINAL",
        "set.desktop": "SET DESKTOP",
        "copy.url": "COPY URL",
        "copied": "COPIED!",
        // Detail
        "wallpaper.detail": "WALLPAPER DETAIL",
        "resolution": "RESOLUTION",
        "category": "CATEGORY",
        "tags": "TAGS",
        "settings": "SETTINGS",
        // Errors
        "error": "ERROR",
        "ok": "OK",
        // Detail actions
        "downloading": "DOWNLOADING...",
        "set.desktop.wallpaper": "SET DESKTOP",
        // Settings
        "proxy": "PROXY",
        "clear.cache": "CLEAR CACHE",
        "clear.cache.message": "Clear all cached images?",
        "cache": "CACHE",
        "download.settings": "DOWNLOAD SETTINGS",
        "auto.download": "AUTO DOWNLOAD ORIGINAL",
        "save.to.downloads": "SAVE TO DOWNLOADS",
        "pro.version": "PRO VERSION",
        "free.version": "FREE VERSION",
        "downloads": "Downloads:",
        "upgrade": "UPGRADE",
        "worker.url": "WORKER URL",
        "configure.proxy": "Configure Cloudflare Worker proxy for improved connectivity.",
        "api.key": "API KEY",
        "api.key.placeholder": "Enter your WallHaven API key",
        "test": "TEST",
        "testing": "TESTING",
        "success": "SUCCESS",
        "failed": "FAILED",
        "version": "VERSION",
        "data.source": "DATA SOURCE",
        "animeSource": "ANIME SOURCE",
        "license": "LICENSE",
        "developer": "DEVELOPER",
        "visit.website": "VISIT WEBSITE",
        "report.issue": "REPORT ISSUE",
        "rate.app": "RATE APP",
        "wallhaven": "WallHaven",
        "startup": "STARTUP",
        "clearCache": "CLEAR CACHE",
        "status": "STATUS",
        // Search
        "search": "SEARCH",
        "back": "BACK",
        "go": "GO",
        "searching": "SEARCHING...",
        "no.results": "NO RESULTS",
        "filter.all": "ALL",
        "filter.general": "GENERAL",
        "filter.anime": "ANIME",
        "filter.nature": "NATURE",
        "filter.people": "PEOPLE",
        "filter.tech": "TECH",
        // My Media
        "my.media.library": "MY MEDIA LIBRARY",
        "my.media.subtitle": "View wallpaper favorites, media favorites, and downloaded content in one place.",
        "items.favorites": "FAVORITES",
        "items": "ITEMS",
        "wallpaper.favorites": "WALLPAPER FAVORITES",
        "media.favorites": "MEDIA FAVORITES",
        "wallpaper.downloads": "DOWNLOADED WALLPAPERS",
        "media.downloads": "DOWNLOADED MEDIA",
        "browse.history": "BROWSE HISTORY",
        "no.wallpaper.favorites": "NO WALLPAPER FAVORITES",
        "no.wallpaper.favorites.hint": "Favorite wallpapers from Home or Explore will appear here.",
        "no.media.favorites": "NO MEDIA FAVORITES",
        "no.media.favorites.hint": "Favorite media from Media Explore will appear here.",
        "no.wallpaper.downloads": "NO DOWNLOADED WALLPAPERS",
        "no.wallpaper.downloads.hint": "Downloaded wallpapers from detail view will be saved here.",
        "no.media.downloads": "NO DOWNLOADED MEDIA",
        "no.media.downloads.hint": "Select quality in media detail to download and save here.",
        "no.history": "NO HISTORY",
        "no.history.hint": "Recently viewed media items will be saved locally here.",
        "badge.favorite": "FAVORITE",
        "badge.recent": "RECENT",
        // Navigation
        "nav.home": "HOME",
        "nav.wallpaper": "WALLPAPER",
        "nav.anime": "ANIME",
        "nav.media": "MEDIA",
        "nav.myMedia": "我的",
        "nav.messages": "消息",
        // Status bar
        "statusbar.showWindow": "Show Window",
        "statusbar.enableWallpaper": "Enable Dynamic Wallpaper",
        "statusbar.disableWallpaper": "Disable Dynamic Wallpaper",
        "statusbar.pauseWallpaper": "Pause Wallpaper",
        "statusbar.resumeWallpaper": "Resume Wallpaper",
        "statusbar.muteWallpaper": "Mute Wallpaper",
        "statusbar.unmuteWallpaper": "Unmute Wallpaper",
        "statusbar.quit": "Quit",
        // Tabs
        "tab.all": "ALL",
        "tab.nature": "NATURE",
        "tab.technology": "TECH",
        // Player
        "player.nowPlaying": "NOW PLAYING",
        "player.selectWallpaper": "SELECT WALLPAPER",
        "player.playlist": "PLAYLIST",
        "player.music": "MUSIC",
        "player.previous": "PREVIOUS",
        "player.play": "PLAY",
        "player.pause": "PAUSE",
        "player.next": "NEXT",
        "player.speed": "SPEED",
        "player.favorite": "FAVORITE",
        "player.unfavorite": "UNFAVORITE",
        // Loading
        "loading": "LOADING...",
        "noData": "NO DATA",
        "loadMore": "LOAD MORE",
        // Errors
        "loadFailed": "LOAD FAILED",
        "retry": "RETRY",
        // Filters
        "contentLevel": "CONTENT LEVEL",
        "colorFilter": "COLOR FILTER",
        "currentFilters": "CURRENT FILTERS",
        "allRatios": "ALL RATIOS",
        // Actions
        "wallpaperCount": "WALLPAPERS",
        "exploreWallpaper": "EXPLORE WALLPAPER",
        "wallpaperLibrary": "EXPLORE WALLPAPER LIBRARY",
        "discoverQuality": "DISCOVER QUALITY WALLPAPERS CURATED FOR YOUR DESKTOP",
        "hotWallpaper": "HOT",
        "exploreMedia": "EXPLORE DYNAMIC MEDIA LIBRARY",
        "hotDynamic": "HOT DYNAMIC WALLPAPERS",
        "latestWallpaper": "LATEST WALLPAPERS",
        "viewWallpaper": "VIEW WALLPAPER",
        // Detail
        "info": "INFO",
        "specs": "SPECS",
        "wallpaperColors": "COLORS",
        "setWallpaper": "SET WALLPAPER",
        "wallpaperContent": "WALLPAPER CONTENT",
        "shareWallpaper": "SHARE WALLPAPER",
        "shareWithEveryone": "SHARE WITH EVERYONE",
        "generateShareable": "GENERATE A SHAREABLE LINK",
        "sendToFriends": "SEND TO FRIENDS",
        "author": "AUTHOR:",
        "size": "SIZE:",
        "likes": "LIKES:",
        "settingWallpaper": "SETTING DESKTOP WALLPAPER...",
        "downloadingWallpaper": "DOWNLOADING WALLPAPER...",
        "savedToDownloads": "SAVED TO DOWNLOADS",
        // Filter view
        "apiKeyRequired": "API KEY REQUIRED",
        "apiKeyNeeded": "Sketchy and NSFW filters require a Wallhaven API Key. Please configure it in Settings.",
        "sketchyNsfwRequire": "Sketchy / NSFW requires API Key in Settings first.",
        "filters.title": "FILTERS",
        // Settings
        "settings.title": "SETTINGS",
        "preferences": "PREFERENCES",
        "general.desc": "Manage language, API permissions, and cache space.",
        "download.desc": "Control auto-download strategy and view current tasks.",
        "scheduler.desc": "Set wallpaper rotation rhythm, order, and content source.",
        "about.desc": "View version info, project background, and external links.",
        "about": "ABOUT",
        "download": "DOWNLOAD",
        "scheduler": "AUTO REPLACE",
        "languageSettings": "LANGUAGE",
        "languageSettingsDesc": "Choose the interface language used across the app.",
        "displayLanguage": "DISPLAY LANGUAGE",
        "languageImmediateApply": "Changes apply immediately to the current interface.",
        "apiAccess": "API ACCESS",
        "apiAccessDesc": "Configure Wallhaven API Key to access restricted content and increase request quota.",
        "getApiKey": "GET API KEY",
        "apiNotConfigured": "NOT CONFIGURED",
        "apiConfigured": "CONFIGURED",
        "afterConfig": "After configuration, browsing restricted content and higher frequency requests will take effect immediately.",
        "appearanceSettings": "APPEARANCE",
        "appearanceSettingsDesc": "Customize visual effects including grain texture overlay.",
        "grainTextureEffect": "Grain Texture",
        "grainTextureEffectDesc": "Apply film grain texture overlay across all pages for a cinematic look.",
        // Content Types
        "content.wallpaper": "Wallpaper",
        "content.anime": "Anime",
        "content.video": "Video",
        "content.wallpapers": "Wallpapers",
        "content.animes": "Anime",
        "content.videos": "Videos",
        "tab.wallpaper": "Wallpapers",
        "tab.anime": "Anime",
        "tab.video": "Videos",
        "library.wallpapers": "My Wallpapers",
        "library.anime": "My Anime",
        "library.videos": "My Videos",
        "library.all": "All Favorites",
        "favorites.wallpaper": "Wallpaper Favorites",
        "favorites.anime": "Anime Favorites",
        "favorites.video": "Video Favorites",
        "anime.favorites": "ANIME FAVORITES",
        "no.anime.favorites": "NO ANIME FAVORITES",
        "no.anime.favorites.hint": "Favorite anime from Anime Explore will appear here.",
        "downloads.wallpaper": "Wallpaper Downloads",
        "downloads.anime": "Anime Downloads",
        "downloads.video": "Video Downloads",
        "watch.history": "Watch History",
        "watch.continue": "Continue Watching",
        "episode": "Ep {number}",
        "episodes": "Episodes",
        "total.episodes": "{count} Episodes",
        "current.episode": "Episode {number}",
        // Anime Detail
        "anime.watch": "WATCH",
        "anime.continueWatch": "CONTINUE",
        "anime.summary": "Summary",
        "anime.info": "Info",
        "anime.airDate": "Air Date",
        "anime.airWeekday": "Update",
        "anime.type": "Type",
        "anime.rating": "Rating",
        "anime.rank": "Rank",
        "anime.type.tv": "TV Series",
        "anime.type.movie": "Movie",
        "anime.type.ova": "OVA",
        "source.rules": "Source Rules",
        "source.rules.desc": "Manage content source parsing rules. Import from URL or GitHub.",
        "install.rule": "Install Rule",
        "install.from.url": "Install from URL",
        "install.from.github": "Install from GitHub",
        "rule.url.placeholder": "https://example.com/rule.json",
        "github.owner": "Repository Owner",
        "github.repo": "Repository Name",
        "github.path": "File Path",
        "github.branch": "Branch",
        "dataSourceProfiles": "DATA SOURCE PROFILES",
        "dataSourceProfilesDesc": "Import, switch, or reset source profiles for wallpaper and media endpoints.",
        "activeProfile": "ACTIVE PROFILE",
        "importProfile": "IMPORT JSON",
        "importFromURL": "FROM URL",
        "testProfile": "TEST PROFILE",
        "resetProfile": "RESET DEFAULT",
        "newProfile": "NEW PROFILE",
        "openConfigDocs": "OPEN DOCS",
        "cacheManagement": "CACHE MANAGEMENT",
        "cacheManagementDesc": "View current cache usage and clear quickly when needed.",
        "cacheUsed": "CACHE USED",
        "thumbnailsTemp": "Total thumbnails and temp files",
        "clearWhenLarge": "Clear cache when usage keeps growing.",
        "downloadPrefs": "DOWNLOAD PREFERENCES",
        "downloadPrefsDesc": "Define auto-download strategy and local save method while browsing.",
        "autoDownloadOriginal": "AUTO DOWNLOAD ORIGINAL",
        "autoDownloadDesc": "Auto cache HD originals while browsing to reduce wait time on next open.",
        "saveToDownloadsFolder": "SAVE TO DOWNLOADS FOLDER",
        "saveToDownloadsDesc": "Downloaded wallpapers are also saved to system downloads for easy organization.",
        "downloadTasks": "DOWNLOAD TASKS",
        "downloadTasksDesc": "View recent download status and quickly check queue.",
        "noDownloadTasks": "NO DOWNLOAD TASKS",
        "downloadTasksHint": "When you start downloading wallpapers, progress will show here.",
        "autoReplace": "AUTO REPLACE",
        "autoReplaceDesc": "When enabled, desktop wallpaper will automatically rotate based on your rhythm.",
        "enableAutoReplace": "ENABLE AUTO REPLACE",
        "currentlyRunning": "Currently running, wallpaper will auto update.",
        "currentlyStopped": "Stopped, you can still manually set wallpaper.",
        "running": "RUNNING",
        "stopped": "STOPPED",
        "recentChange": "RECENT CHANGE",
        "replaceRhythm": "REPLACE RHYTHM",
        "replaceRhythmDesc": "Set rotation interval, playback order, and wallpaper source.",
        "replaceInterval": "REPLACE INTERVAL",
        "intervalDesc": "Determines auto-switch frequency.",
        "interval": "INTERVAL",
        "replaceOrder": "REPLACE ORDER",
        "sequential": "SEQUENTIAL",
        "wallpaperSource": "WALLPAPER SOURCE",
        "online": "ONLINE",
        "local": "LOCAL",
        "versionInfo": "VERSION",
        "elegantApp": "Elegant macOS Wallpaper Browser",
        "projectInfo": "PROJECT INFO",
        "projectInfoDesc": "Quickly understand app origin and tech stack.",
        "dataSource": "DATA SOURCE",
        "techStack": "TECH STACK",
        "externalLinks": "EXTERNAL LINKS",
        "externalLinksDesc": "Visit official site or feedback portal.",
        "visitWebsite": "VISIT WEBSITE",
        "visitWebsiteDesc": "Browse wallhaven.cc official gallery.",
        "reportProblem": "REPORT PROBLEM",
        "reportProblemDesc": "Submit bugs, suggestions, or product feedback.",
        "minutes": "MINUTES",
        "hour": "HOUR",
        "hours": "HOURS",
        // Status
        "status.pending": "PENDING",
        "status.downloading": "DOWNLOADING",
        "status.paused": "PAUSED",
        "status.completed": "COMPLETED",
        "status.failed": "FAILED",
        "status.cancelled": "CANCELLED",
        // Media detail
        "specs2": "SPECS",
        "duration": "DURATION",
        "download2": "DOWNLOAD",
        "title": "TITLE",
        "page": "PAGE",
        "resolution2": "RESOLUTION",
        "format2": "FORMAT",
        "audio2": "AUDIO",
        "muted": "MUTED",
        "audioOn": "ON",
        "noDownloadOptions": "NONE",
        "source": "SOURCE",
        "downloadSources": "DOWNLOAD SOURCES",
        "applyingWallpaper": "APPLYING MP4 DYNAMIC WALLPAPER...",
        "downloadingMedia": "DOWNLOADING DYNAMIC MEDIA...",
        // Editor
        "edit": "EDIT",
        "done": "DONE",
        "selectAll": "SELECT ALL",
        "deselectAll": "DESELECT ALL",
        "selected": "SELECTED",
        "delete": "DELETE",
        // Sort
        "sort.hot": "HOT",
        "sort.latest": "LATEST",
        "sort.views": "VIEWS",
        "sort.likes": "LIKES",
        "sort.toplist": "TOPLIST",
        "sort.random": "RANDOM",
        "sort.relevance": "RELEVANCE",
        "sort.newest": "NEWEST",
        "sort.title2": "TITLE",
        "sort.format2": "FORMAT",
        "sortByNewest": "SORT BY NEWEST",
        "sortByTitle": "SORT BY TITLE",
        "sortByFormat": "SORT BY FORMAT",
        // Purity
        "purity.sfw": "SAFE CONTENT",
        "purity.sketchy": "MILD SENSITIVE",
        "purity.nsfw": "ADULT CONTENT",
        // Aspect ratios
        "aspect.ultrawide": "ULTRAWIDE",
        "aspect.dynamic": "DYNAMIC",
        "aspect.loop": "LOOP",
        "aspect.aesthetic": "AESTHETIC",
        // Media type
        "media.count": "MEDIA",
        "media.loaded": "LOADED",
        "ascending2": "ASCENDING",
        "descending2": "DESCENDING",
        // Media categories
        "filter.hd": "HD",
        "filter.game": "GAME",
        "filter.rain": "RAIN",
        "filter.cyberpunk": "CYBERPUNK",
        "filter.nature2": "NATURE",
        "filter.dark": "DARK",
        "filter.games": "GAMES",
        "filter.superhero": "SUPERHERO",
        "filter.car": "CAR",
        "filter.tv": "TV",
        "filter.fantasy": "FANTASY",
        "filter.space": "SPACE",
        "filter.technology2": "TECHNOLOGY",
        "filter.holiday": "HOLIDAY",
        "filter.animal": "ANIMAL",
        "filter.horror": "HORROR",
        "filter.football": "FOOTBALL",
        "filter.japan": "JAPAN",
        // Empty states
        "noMediaFilter": "NO MEDIA WITH CURRENT FILTER",
        "tryDifferentFilter": "TRY A DIFFERENT CATEGORY, TAG, OR SEARCH TERM.",
        "noMoreResults": "NO MORE RESULTS",
        "allLoaded": "ALL LOADED",
        "mediaUnavailable": "MEDIA UNAVAILABLE",
        // Additional
        "noMessages": "NO MESSAGES YET",
        "unknown": "UNKNOWN",
        "created": "CREATED",
        "ratio": "RATIO",
        "fileType": "TYPE",
        "shareLinkDescription": "Anyone with the link can open the same Wallhaven resource in their browser or save it locally.",
        "videoMutedPlaying": "Background video muted and looping",
        "videoPlaying": "Background video looping",
        "versions": "VERSIONS",
        // Settings additional
        "clearCacheConfirm": "Are you sure you want to clear all cache? This will delete downloaded thumbnails and temp files.",
        // Settings - Update Check
        "apiKey": "API KEY",
        "ruleRepository": "RULE REPOSITORY",
        "ruleRepositoryDesc": "Configure GitHub repository URL to auto-sync wallpaper, media, and anime rules.",
        "configured": "Configured",
        "checkForUpdates": "CHECK FOR UPDATES",
        "downloadUpdate": "DOWNLOAD UPDATE",
        "newVersionAvailable": "New version available",
        "goToDownload": "GO TO DOWNLOAD",
        "alreadyLatestVersion": "You are using the latest version.",
        "newVersionFound": "New version found:",
        "goToDownloadQuestion": "Would you like to go to download?",
        "networkProxy": "NETWORK PROXY",
        "networkProxyDesc": "Chinese users can access WallHaven via self-hosted Cloudflare Worker.",
        "customWorkerUrl": "CUSTOM WORKER URL",
        "notConfiguredDirect": "NOT CONFIGURED (DIRECT)",
        "deploymentGuide": "DEPLOYMENT GUIDE",
        "afterWorkerConfig": "After filling in, WallHaven requests will prioritize your Worker proxy for VPN-free access.",
        "mediaError": "MEDIA ERROR",
        "searchWallpaper": "SEARCH WALLPAPER...",
        // Profile Editor
        "editProfile": "EDIT PROFILE",
        "save": "SAVE",
        "pleaseFixErrors": "Please fix validation errors",
        "basicInfo": "BASIC INFO",
        "basicInfoDesc": "Profile identification and description.",
        "profileID": "Profile ID",
        "profileName": "Profile Name",
        "profileNamePlaceholder": "My Custom Profile",
        "profileDescription": "Description",
        "profileDescriptionPlaceholder": "Optional description for this profile",
        "wallpaperConfig": "WALLPAPER CONFIG",
        "wallpaperConfigDesc": "API endpoints and URL templates for wallpapers.",
        "provider": "Provider",
        "displayName": "Display Name",
        "apiBaseURL": "API Base URL",
        "searchPath": "Search Path",
        "wallpaperPath": "Wallpaper Path",
        "wallpaperPathHelp": "Use {id} for wallpaper ID",
        "imageURLTemplate": "Image URL Template",
        "imageURLTemplateHelp": "Use {prefix}, {id}, {ext} as placeholders",
        "authHeaderName": "Auth Header Name",
        "mediaConfig": "MEDIA CONFIG",
        "mediaConfigDesc": "Media source base configuration.",
        "baseURL": "Base URL",
        "headers": "HEADERS",
        "headersDesc": "HTTP headers sent with media requests.",
        "headerKey": "Key",
        "headerValue": "Value",
        "addHeader": "Add Header",
        "routes": "ROUTES",
        "routesDesc": "URL patterns for different media pages.",
        "routeHome": "Home",
        "routeMobile": "Mobile",
        "routeTag": "Tag",
        "routeTagHelp": "Use {slug} for tag identifier",
        "routeSearch": "Search",
        "routeSearchHelp": "Use {query} for search term",
        "routeDetail": "Detail",
        "routeDetailHelp": "Use {slug} for item identifier",
        "parsing": "PARSING",
        "parsingDesc": "Regex patterns for extracting media data.",
        "listItemPatterns": "List Item Patterns",
        "listItemPatternsDesc": "Patterns to extract items from list pages",
        "nextPagePatterns": "Next Page Patterns",
        "nextPagePatternsDesc": "Patterns to find next page URL",
        "addPattern": "Add Pattern",
        "tagPattern": "Tag Pattern",
        "tagPatternPlaceholder": "Pattern to extract tags...",
        "downloadPattern": "Download Pattern",
        "downloadPatternPlaceholder": "Pattern to extract download links...",
        "durationPattern": "Duration Pattern",
        "durationPatternPlaceholder": "Pattern to extract video duration...",
        // Network & Error States
        "error.network.title": "CONNECTION ERROR",
        "error.network.message": "Unable to connect to the server. Please check your network connection and try again.",
        "error.empty.title": "NO CONTENT",
        "error.empty.message": "No items found for the current filter. Try adjusting your search or filters.",
        "error.server.title": "SERVER ERROR",
        "error.server.message": "The server encountered an error. Please try again later.",
        "error.offline.title": "OFFLINE",
        "error.offline.message": "You appear to be offline. Please check your network connection.",
        "error.unknown.title": "SOMETHING WENT WRONG",
        "error.unknown.message": "An unexpected error occurred. Please try again.",
        "tap.to.retry": "Tap to retry",
        "network.wifi": "WiFi",
        "network.cellular": "Cellular",
        "network.connected": "Connected",
        "network.offline": "Offline",
        "weak.network.message": "Weak network connection. Some content may load slowly.",
        "offline.title": "You're Offline",
        "offline.message": "Check your connection and try again. Cached content may still be available."
    ],
    .chinese: [
        // Launch at Login
        "launchAtLogin": "开机启动",
        "launchAtLoginDesc": "登录时自动启动 WallHaven。",
        "launchAtLoginSubtitle": "启动后最小化到菜单栏，自动应用动态壁纸。",
        // Categories
        "category.general": "通用",
        "category.anime": "动漫",
        "category.people": "人物",
        "category.nature": "自然",
        "category.technology": "科技",
        // UI
        "search.placeholder": "搜索...",
        "filters": "筛选",
        "reset.all": "重置全部",
        "apply.filters": "应用筛选",
        "cancel": "取消",
        // Sections
        "featured": "精选",
        "view.all": "查看全部",
        "all.wallpapers": "全部壁纸",
        "loading.more": "加载更多...",
        "no.wallpapers": "未找到壁纸",
        // Filter
        "categories": "分类",
        "purity": "纯净度",
        "sorting": "排序",
        "resolutions": "分辨率",
        "ratios": "比例",
        "colors": "颜色",
        "sfw": "安全",
        "sketchy": "可疑",
        "nsfw": "限制",
        "descending": "降序",
        "ascending": "升序",
        "top.range": "热门范围:",
        "date": "日期",
        "date.added": "添加日期",
        "views": "浏览",
        "favorites": "收藏",
        "toplist": "排行",
        "random": "随机",
        "relevance": "相关",
        "order": "顺序",
        "general": "通用",
        "anime": "动漫",
        "people": "人物",
        "more.filters": "更多",
        "clear": "清除",
        // Colors
        "color.red": "红色",
        "color.green": "绿色",
        "color.blue": "蓝色",
        "color.yellow": "黄色",
        "color.purple": "紫色",
        "color.teal": "青色",
        "color.orange": "橙色",
        "color.violet": "紫罗兰",
        "color.skyblue": "天蓝",
        "color.gray": "灰色",
        "color.black": "黑色",
        "color.white": "白色",
        // Actions
        "download.original": "下载原图",
        "set.desktop": "设为桌面",
        "copy.url": "复制链接",
        "copied": "已复制!",
        // Detail
        "wallpaper.detail": "壁纸详情",
        "resolution": "分辨率",
        "category": "分类",
        "tags": "标签",
        "settings": "设置",
        // Errors
        "error": "错误",
        "ok": "确定",
        // Detail actions
        "downloading": "下载中...",
        "set.desktop.wallpaper": "设为桌面壁纸",
        // Settings
        "proxy": "代理",
        "clear.cache": "清除缓存",
        "clear.cache.message": "确定清除所有缓存图片吗？",
        "cache": "缓存",
        "download.settings": "下载设置",
        "auto.download": "自动下载原图",
        "save.to.downloads": "保存到下载",
        "pro.version": "专业版",
        "free.version": "免费版",
        "downloads": "下载次数:",
        "upgrade": "升级",
        "worker.url": "Worker URL",
        "configure.proxy": "配置 Cloudflare Worker 代理以改善网络连接。",
        "api.key": "API Key",
        "api.key.placeholder": "输入您的 WallHaven API Key",
        "test": "测试",
        "testing": "测试中",
        "success": "成功",
        "failed": "失败",
        "version": "版本",
        "data.source": "数据来源",
        "animeSource": "动漫来源",
        "license": "许可证",
        "developer": "开发者",
        "visit.website": "访问网站",
        "report.issue": "报告问题",
        "rate.app": "评价应用",
        "wallhaven": "WallHaven",
        "startup": "启动设置",
        "clearCache": "清除缓存",
        "status": "状态",
        // Search
        "search": "搜索",
        "back": "返回",
        "go": "搜索",
        "searching": "搜索中...",
        "no.results": "无结果",
        "filter.all": "全部",
        "filter.general": "一般",
        "filter.anime": "动漫",
        "filter.nature": "自然",
        "filter.people": "人物",
        "filter.tech": "科技",
        // My Media
        "my.media.library": "我的库",
        "my.media.subtitle": "集中查看壁纸收藏、动态媒体收藏和已下载素材。",
        "items.favorites": "项收藏",
        "items": "项",
        "wallpaper.favorites": "壁纸收藏",
        "media.favorites": "媒体收藏",
        "wallpaper.downloads": "已下载壁纸",
        "media.downloads": "已下载媒体",
        "browse.history": "浏览历史",
        "no.wallpaper.favorites": "还没有收藏壁纸",
        "no.wallpaper.favorites.hint": "在首页或壁纸探索页点亮心形后，这里会自动同步。",
        "no.media.favorites": "还没有收藏动态媒体",
        "no.media.favorites.hint": "在媒体探索页点亮心形后，这里会自动同步。",
        "no.wallpaper.downloads": "还没有下载壁纸",
        "no.wallpaper.downloads.hint": "在壁纸详情或全屏预览中下载后，这里会保留本地记录。",
        "no.media.downloads": "还没有下载媒体",
        "no.media.downloads.hint": "在媒体详情里选择清晰度后，会保存到下载目录并同步到这里。",
        "no.history": "历史记录为空",
        "no.history.hint": "打开媒体详情后，最近浏览过的内容会保存在本地。",
        "badge.favorite": "收藏",
        "badge.recent": "最近",
        // Navigation
        "nav.home": "首页",
        "nav.wallpaper": "壁纸",
        "nav.anime": "动漫",
        "nav.media": "媒体",
        "nav.myMedia": "我的",
        "nav.messages": "消息",
        // Status bar
        "statusbar.showWindow": "显示主窗口",
        "statusbar.enableWallpaper": "开启动态壁纸",
        "statusbar.disableWallpaper": "关闭动态壁纸",
        "statusbar.pauseWallpaper": "暂停动态壁纸",
        "statusbar.resumeWallpaper": "继续动态壁纸",
        "statusbar.muteWallpaper": "静音动态壁纸",
        "statusbar.unmuteWallpaper": "取消静音",
        "statusbar.quit": "退出",
        // Tabs
        "tab.all": "全部",
        "tab.nature": "风景",
        "tab.technology": "技术",
        // Player
        "player.nowPlaying": "正在播放",
        "player.selectWallpaper": "选择壁纸",
        "player.playlist": "播放列表",
        "player.music": "音乐",
        "player.previous": "上一首",
        "player.play": "播放",
        "player.pause": "暂停",
        "player.next": "下一首",
        "player.speed": "速度",
        "player.favorite": "收藏",
        "player.unfavorite": "取消收藏",
        // Loading
        "loading": "加载中...",
        "noData": "暂无数据",
        "loadMore": "加载更多",
        // Errors
        "loadFailed": "加载失败",
        "retry": "重试",
        // Filters
        "contentLevel": "内容级别",
        "colorFilter": "颜色筛选",
        "currentFilters": "当前筛选",
        "allRatios": "全部比例",
        // Actions
        "wallpaperCount": "张壁纸",
        "exploreWallpaper": "探索壁纸",
        "wallpaperLibrary": "探索壁纸资源库",
        "discoverQuality": "探索为您的桌面精选的高质量壁纸",
        "hotWallpaper": "热门",
        "exploreMedia": "探索动态媒体库",
        "hotDynamic": "热门动态壁纸",
        "latestWallpaper": "最新壁纸",
        "viewWallpaper": "查看壁纸",
        // Detail
        "info": "信息",
        "specs": "规格",
        "wallpaperColors": "颜色",
        "setWallpaper": "设为壁纸",
        "wallpaperContent": "壁纸内容",
        "shareWallpaper": "分享壁纸",
        "shareWithEveryone": "与所有人分享此壁纸",
        "generateShareable": "生成一个可分享的链接",
        "sendToFriends": "与朋友分享",
        "author": "作者:",
        "size": "大小:",
        "likes": "喜欢:",
        "settingWallpaper": "正在设置桌面壁纸...",
        "downloadingWallpaper": "正在下载原图...",
        "savedToDownloads": "已保存到本地下载目录",
        // Filter view
        "apiKeyRequired": "需要 API Key",
        "apiKeyNeeded": "Sketchy 和 NSFW 过滤依赖 Wallhaven API Key。请先在设置页配置有效的 API Key。",
        "sketchyNsfwRequire": "Sketchy / NSFW 需要先在设置中配置 Wallhaven API Key。",
        "filters.title": "筛选",
        // Settings
        "settings.title": "设置",
        "preferences": "偏好设置",
        "general.desc": "管理语言、API 权限与缓存空间。",
        "download.desc": "控制自动下载策略，并查看当前任务状态。",
        "scheduler.desc": "设定壁纸轮换节奏、顺序和素材来源。",
        "about.desc": "查看版本信息、项目背景与外部链接。",
        "about": "关于",
        "download": "下载",
        "scheduler": "自动更换",
        "languageSettings": "语言设置",
        "languageSettingsDesc": "选择整个应用界面使用的语言。",
        "displayLanguage": "显示语言",
        "languageImmediateApply": "切换后会立即应用到当前界面。",
        "apiAccess": "API 接入",
        "apiAccessDesc": "配置 WallHaven API Key 后可访问受限内容并提升请求额度。",
        "getApiKey": "获取 API Key",
        "apiNotConfigured": "未配置",
        "apiConfigured": "已配置",
        "afterConfig": "配置完成后，浏览受限内容与更高频请求都会立即生效。",
        "appearanceSettings": "外观设置",
        "appearanceSettingsDesc": "自定义视觉效果，包括颗粒材质覆盖层。",
        "grainTextureEffect": "颗粒材质",
        "grainTextureEffectDesc": "在所有页面应用胶片颗粒纹理效果，营造电影质感。",
        // Content Types
        "content.wallpaper": "壁纸",
        "content.anime": "动漫",
        "content.video": "视频",
        "content.wallpapers": "壁纸",
        "content.animes": "动漫",
        "content.videos": "视频",
        "tab.wallpaper": "壁纸",
        "tab.anime": "动漫",
        "tab.video": "视频",
        "library.wallpapers": "我的壁纸",
        "library.anime": "我的动漫",
        "library.videos": "我的视频",
        "library.all": "全部收藏",
        "favorites.wallpaper": "壁纸收藏",
        "favorites.anime": "动漫收藏",
        "favorites.video": "视频收藏",
        "anime.favorites": "动漫收藏",
        "no.anime.favorites": "还没有收藏动漫",
        "no.anime.favorites.hint": "在动漫探索页点亮心形后，这里会自动同步。",
        "downloads.wallpaper": "壁纸下载",
        "downloads.anime": "动漫下载",
        "downloads.video": "视频下载",
        "watch.history": "观看历史",
        "watch.continue": "继续观看",
        "episode": "第{number}集",
        "episodes": "剧集",
        "total.episodes": "共{count}集",
        "current.episode": "看到第{number}集",
        // Anime Detail
        "anime.watch": "观看",
        "anime.continueWatch": "继续观看",
        "anime.summary": "简介",
        "anime.info": "信息",
        "anime.airDate": "首播日期",
        "anime.airWeekday": "更新时间",
        "anime.type": "类型",
        "anime.rating": "评分",
        "anime.rank": "排名",
        "anime.type.tv": "电视动画",
        "anime.type.movie": "剧场版",
        "anime.type.ova": "OVA",
        "source.rules": "数据源规则",
        "source.rules.desc": "管理内容源的解析规则，支持从URL或GitHub导入。",
        "install.rule": "安装规则",
        "install.from.url": "从URL安装",
        "install.from.github": "从GitHub安装",
        "rule.url.placeholder": "https://example.com/rule.json",
        "github.owner": "仓库所有者",
        "github.repo": "仓库名",
        "github.path": "文件路径",
        "github.branch": "分支",
        "dataSourceProfiles": "数据源配置",
        "dataSourceProfilesDesc": "导入、切换或恢复壁纸与媒体接口配置。",
        "activeProfile": "当前配置",
        "importProfile": "导入 JSON",
        "importFromURL": "从 URL 导入",
        "testProfile": "测试配置",
        "resetProfile": "恢复默认",
        "openConfigDocs": "打开文档",
        "newProfile": "新建配置",
        "cacheManagement": "缓存管理",
        "cacheManagementDesc": "查看当前缓存占用，并在需要时快速清理。",
        "cacheUsed": "已使用缓存",
        "thumbnailsTemp": "缩略图和临时文件总量",
        "clearWhenLarge": "当缓存占用持续变大时，可以清除后重新生成。",
        "downloadPrefs": "下载偏好",
        "downloadPrefsDesc": "定义浏览时的自动下载策略和本地保存方式。",
        "autoDownloadOriginal": "自动下载原图",
        "autoDownloadDesc": "浏览时自动缓存高清原图，减少再次打开的等待时间。",
        "saveToDownloadsFolder": "保存到下载文件夹",
        "saveToDownloadsDesc": "下载的壁纸会额外保存到系统下载目录，方便后续整理。",
        "downloadTasks": "下载任务",
        "downloadTasksDesc": "查看近期下载状态，快速了解当前队列情况。",
        "noDownloadTasks": "暂无下载任务",
        "downloadTasksHint": "当你开始下载壁纸时，任务进度会显示在这里。",
        "autoReplace": "自动更换",
        "autoReplaceDesc": "开启后会按照你设定的节奏自动轮换桌面壁纸。",
        "enableAutoReplace": "启用自动更换",
        "currentlyRunning": "当前正在按计划执行，壁纸会自动更新。",
        "currentlyStopped": "关闭状态下不会自动切换，你仍可手动设置壁纸。",
        "running": "运行中",
        "stopped": "已停止",
        "recentChange": "最近更换",
        "replaceRhythm": "更换节奏",
        "replaceRhythmDesc": "设置轮换间隔、播放顺序和壁纸来源。",
        "replaceInterval": "更换间隔",
        "intervalDesc": "决定自动切换的频率。",
        "interval": "间隔",
        "replaceOrder": "更换顺序",
        "sequential": "顺序",
        "wallpaperSource": "壁纸来源",
        "online": "在线",
        "local": "本地",
        "versionInfo": "版本",
        "elegantApp": "优雅的 macOS 壁纸浏览器",
        "projectInfo": "项目信息",
        "projectInfoDesc": "快速了解这个应用的来源与技术栈。",
        "dataSource": "数据来源",
        "techStack": "技术栈",
        "externalLinks": "外部链接",
        "externalLinksDesc": "访问官网或前往反馈入口。",
        "visitWebsite": "访问网站",
        "visitWebsiteDesc": "浏览 wallhaven.cc 的官方图库。",
        "reportProblem": "反馈问题",
        "reportProblemDesc": "提交 bug、建议或产品反馈。",
        "minutes": "分钟",
        "hour": "小时",
        "hours": "小时",
        // Status
        "status.pending": "等待中",
        "status.downloading": "下载中",
        "status.paused": "已暂停",
        "status.completed": "已完成",
        "status.failed": "失败",
        "status.cancelled": "已取消",
        // Media detail
        "source": "来源",
        "specs2": "规格",
        "duration": "时长",
        "download2": "下载",
        "title": "标题",
        "page": "页面",
        "resolution2": "分辨率",
        "format2": "格式",
        "audio2": "音频",
        "muted": "默认静音",
        "audioOn": "已开启",
        "noDownloadOptions": "暂无",
        "downloadSources": "下载源",
        "applyingWallpaper": "正在应用 mp4 动态壁纸...",
        "downloadingMedia": "正在下载动态壁纸资源...",
        // Editor
        "edit": "编辑",
        "done": "完成",
        "selectAll": "全选",
        "deselectAll": "取消全选",
        "selected": "已选择",
        "delete": "删除",
        // Sort
        "sort.hot": "热门",
        "sort.latest": "最新",
        "sort.views": "浏览量",
        "sort.likes": "喜欢数",
        "sort.toplist": "排行榜",
        "sort.random": "随机",
        "sort.relevance": "相关度",
        "sort.newest": "最新",
        "sort.title2": "标题",
        "sort.format2": "规格",
        "sortByNewest": "按最新载入排序",
        "sortByTitle": "按标题排序",
        "sortByFormat": "按规格排序",
        // Purity
        "purity.sfw": "安全内容",
        "purity.sketchy": "轻度敏感",
        "purity.nsfw": "成人内容",
        // Aspect ratios
        "aspect.ultrawide": "超宽屏",
        "aspect.dynamic": "动态",
        "aspect.loop": "循环",
        "aspect.aesthetic": "美学",
        // Media type
        "media.count": "段媒体",
        "media.loaded": "已加载",
        "ascending2": "升序排列",
        "descending2": "降序排列",
        // Media categories
        "filter.hd": "高清",
        "filter.game": "游戏",
        "filter.rain": "雨天",
        "filter.cyberpunk": "赛博朋克",
        "filter.nature2": "自然",
        "filter.dark": "暗黑",
        "filter.games": "游戏",
        "filter.superhero": "超级英雄",
        "filter.car": "汽车",
        "filter.tv": "影视",
        "filter.fantasy": "幻想",
        "filter.space": "太空",
        "filter.technology2": "科技",
        "filter.holiday": "节日",
        "filter.animal": "动物",
        "filter.horror": "恐怖",
        "filter.football": "足球",
        "filter.japan": "日本",
        // Empty states
        "noMediaFilter": "当前筛选下没有媒体",
        "tryDifferentFilter": "换一个分类、热门标签或搜索关键词再试。",
        "noMoreResults": "当前没有更多结果",
        "allLoaded": "已加载",
        "mediaUnavailable": "媒体资源暂时不可用",
        // Additional
        "noMessages": "暂无消息",
        "unknown": "未知",
        "created": "创建时间",
        "ratio": "比例",
        "fileType": "类型",
        "shareLinkDescription": "任何拥有链接的人都可以在浏览器中打开相同的 Wallhaven 资源或将其保存到本地。",
        "videoMutedPlaying": "背景视频默认静音循环播放",
        "videoPlaying": "背景视频正在循环播放",
        "versions": "个版本",
        // Settings additional
        "clearCacheConfirm": "确定要清除所有缓存吗？这将删除已下载的缩略图和临时文件。",
        "networkProxy": "网络代理",
        "networkProxyDesc": "国内用户可通过自建 Cloudflare Worker 访问 WallHaven。",
        "customWorkerUrl": "自定义 Worker URL",
        "notConfiguredDirect": "未配置（直连 WallHaven）",
        "deploymentGuide": "部署教程",
        "afterWorkerConfig": "填写后，WallHaven 相关请求将优先走你的 Worker 代理，无需 VPN 即可访问。",
        "mediaError": "媒体错误",
        "searchWallpaper": "搜索壁纸...",
        // Profile Editor
        "editProfile": "编辑配置",
        "save": "保存",
        "pleaseFixErrors": "请修复验证错误",
        "basicInfo": "基础信息",
        "basicInfoDesc": "配置标识和描述信息。",
        "profileID": "配置 ID",
        "profileName": "配置名称",
        "profileNamePlaceholder": "我的自定义配置",
        "profileDescription": "描述",
        "profileDescriptionPlaceholder": "为此配置添加可选描述",
        "wallpaperConfig": "壁纸配置",
        "wallpaperConfigDesc": "壁纸 API 端点和 URL 模板设置。",
        "provider": "提供者",
        "displayName": "显示名称",
        "apiBaseURL": "API 基础 URL",
        "searchPath": "搜索路径",
        "wallpaperPath": "壁纸路径",
        "wallpaperPathHelp": "使用 {id} 表示壁纸 ID",
        "imageURLTemplate": "图片 URL 模板",
        "imageURLTemplateHelp": "使用 {prefix}、{id}、{ext} 作为占位符",
        "authHeaderName": "认证头部名称",
        "mediaConfig": "媒体配置",
        "mediaConfigDesc": "媒体源基础配置。",
        "baseURL": "基础 URL",
        "headers": "请求头",
        "headersDesc": "发送媒体请求时使用的 HTTP 头部。",
        "headerKey": "键",
        "headerValue": "值",
        "addHeader": "添加头部",
        "routes": "路由",
        "routesDesc": "不同媒体页面的 URL 模式。",
        "routeHome": "首页",
        "routeMobile": "移动端",
        "routeTag": "标签页",
        "routeTagHelp": "使用 {slug} 表示标签标识",
        "routeSearch": "搜索页",
        "routeSearchHelp": "使用 {query} 表示搜索词",
        "routeDetail": "详情页",
        "routeDetailHelp": "使用 {slug} 表示项目标识",
        "parsing": "解析",
        "parsingDesc": "提取媒体数据的正则表达式模式。",
        "listItemPatterns": "列表项模式",
        "listItemPatternsDesc": "从列表页面提取项目的模式",
        "nextPagePatterns": "下一页模式",
        "nextPagePatternsDesc": "查找下一页 URL 的模式",
        "addPattern": "添加模式",
        "tagPattern": "标签模式",
        "tagPatternPlaceholder": "提取标签的模式...",
        "downloadPattern": "下载模式",
        "downloadPatternPlaceholder": "提取下载链接的模式...",
        "durationPattern": "时长模式",
        "durationPatternPlaceholder": "提取视频时长的模式...",
        // Network & Error States
        "error.network.title": "连接错误",
        "error.network.message": "无法连接到服务器。请检查网络连接后重试。",
        "error.empty.title": "暂无内容",
        "error.empty.message": "当前筛选条件下没有找到内容。请尝试调整搜索或筛选条件。",
        "error.server.title": "服务器错误",
        "error.server.message": "服务器遇到错误。请稍后重试。",
        "error.offline.title": "离线状态",
        "error.offline.message": "您似乎处于离线状态。请检查网络连接。",
        "error.unknown.title": "出错了",
        "error.unknown.message": "发生未知错误。请重试。",
        "tap.to.retry": "点击重试",
        "network.wifi": "WiFi",
        "network.cellular": "蜂窝网络",
        "network.connected": "已连接",
        "network.offline": "离线",
        "weak.network.message": "网络连接较弱，部分内容可能加载缓慢",
        "offline.title": "您已离线",
        "offline.message": "请检查网络连接后重试。缓存内容仍可查看。",
        // Settings - Update Check
        "apiKey": "API Key",
        "ruleRepository": "规则仓库",
        "ruleRepositoryDesc": "配置 GitHub 仓库地址，自动同步壁纸、媒体、动漫规则。",
        "configured": "已配置",
        "checkForUpdates": "检查更新",
        "downloadUpdate": "下载更新",
        "newVersionAvailable": "新版本可用",
        "goToDownload": "前往下载",
        "alreadyLatestVersion": "当前已是最新版本",
        "newVersionFound": "发现新版本",
        "goToDownloadQuestion": "是否前往下载？"
    ],
    .japanese: [
        // Launch at Login
        "launchAtLogin": "ログイン時に起動",
        "launchAtLoginDesc": "ログイン時にWallHavenを自動的に起動します。",
        "launchAtLoginSubtitle": "起動後はメニューバーに最小化され、動的壁纸を自動的に適用します。",
        // Categories
        "category.general": "一般",
        "category.anime": "アニメ",
        "category.people": "人物",
        "category.nature": "自然",
        "category.technology": "テクノロジー",
        // UI
        "search.placeholder": "検索...",
        "filters": "フィルター",
        "reset.all": "すべてリセット",
        "apply.filters": "フィルターを適用",
        "cancel": "キャンセル",
        // Sections
        "featured": "注目",
        "view.all": "すべて表示",
        "all.wallpapers": "すべての壁纸",
        "loading.more": "もっと読み込む...",
        "no.wallpapers": "壁纸が見つかりません",
        // Filter
        "categories": "カテゴリー",
        "purity": "純度",
        "sorting": "並べ替え",
        "resolutions": "解像度",
        "ratios": "比率",
        "colors": "色",
        "sfw": "安全",
        "sketchy": "要注意",
        "nsfw": "制限",
        "descending": "降順",
        "ascending": "昇順",
        "top.range": "トップ範囲:",
        "date": "日付",
        "date.added": "追加日",
        "views": "閲覧",
        "favorites": "お気に入り",
        "toplist": "ランキング",
        "random": "ランダム",
        "relevance": "関連性",
        "order": "順序",
        "general": "一般",
        "anime": "アニメ",
        "people": "人物",
        "more.filters": "もっと",
        // Colors
        "color.red": "赤",
        "color.green": "緑",
        "color.blue": "青",
        "color.yellow": "黄色",
        "color.purple": "紫",
        "color.teal": "ティール",
        "color.orange": "オレンジ",
        "color.violet": "スミレ",
        "color.skyblue": "空色",
        "color.gray": "グレー",
        "color.black": "黒",
        "color.white": "白",
        // Actions
        "download.original": "オリジナルをダウンロード",
        "set.desktop": "デスクトップに設定",
        "copy.url": "URLをコピー",
        "copied": "コピーしました!",
        // Detail
        "wallpaper.detail": "壁纸の詳細",
        "resolution": "解像度",
        "category": "カテゴリー",
        "tags": "タグ",
        "settings": "設定",
        // Errors
        "error": "エラー",
        "ok": "OK",
        // Detail actions
        "downloading": "ダウンロード中...",
        "set.desktop.wallpaper": "デスクトップ壁纸に設定",
        // Settings
        "proxy": "プロキシ",
        "about": "情報",
        "clear.cache": "キャッシュをクリア",
        "clear.cache.message": "すべてのキャッシュ画像をクリアしますか？",
        "clear": "クリア",
        "cache": "キャッシュ",
        "download.settings": "ダウンロード設定",
        "auto.download": "オリジナルを自動ダウンロード",
        "save.to.downloads": "ダウンロードに保存",
        "pro.version": "プロ版",
        "free.version": "無料版",
        "downloads": "ダウンロード:",
        "upgrade": "アップグレード",
        "worker.url": "Worker URL",
        "configure.proxy": "接続を改善するためのCloudflare Workerプロキシを設定します。",
        "api.key": "API Key",
        "api.key.placeholder": "WallHaven API Keyを入力",
        "test": "テスト",
        "testing": "テスト中",
        "success": "成功",
        "failed": "失敗",
        "version": "バージョン",
        "data.source": "データソース",
        "animeSource": "アニメソース",
        "developer": "開発者",
        "license": "ライセンス",
        "visit.website": "ウェブサイト訪問",
        "report.issue": "問題を報告",
        "rate.app": "アプリを評価",
        "wallhaven": "WallHaven",
        "startup": "起動設定",
        "clearCache": "キャッシュをクリア",
        "status": "状態",
        // Search
        "search": "検索",
        "back": "戻る",
        "go": "検索",
        "searching": "検索中...",
        "no.results": "結果なし",
        "filter.all": "すべて",
        "filter.general": "一般",
        "filter.anime": "アニメ",
        "filter.nature": "自然",
        "filter.people": "人物",
        "filter.tech": "テクノロジー",
        // My Media
        "my.media.library": "マイメディアライブラリ",
        "my.media.subtitle": "壁紙のお気に入り、メディアのお気に入り、ダウンロードしたコンテンツを一箇所で確認できます。",
        "items.favorites": "お気に入り",
        "items": "アイテム",
        "wallpaper.favorites": "壁紙お気に入り",
        "media.favorites": "メディアお気に入り",
        "wallpaper.downloads": "ダウンロードした壁紙",
        "media.downloads": "ダウンロードしたメディア",
        "browse.history": "閲覧履歴",
        "no.wallpaper.favorites": "お気に入りの壁紙はありません",
        "no.wallpaper.favorites.hint": "ホームや探索ページでハートをタップすると、ここに表示されます。",
        "no.media.favorites": "お気に入りのメディアはありません",
        "no.media.favorites.hint": "メディア探索ページでハートをタップすると、ここに表示されます。",
        "no.wallpaper.downloads": "ダウンロードした壁紙はありません",
        "no.wallpaper.downloads.hint": "詳細ビューでダウンロードした壁紙はここに保存されます。",
        "no.media.downloads": "ダウンロードしたメディアはありません",
        "no.media.downloads.hint": "メディア詳細で画質を選択してダウンロードすると、ここに保存されます。",
        "no.history": "履歴はありません",
        "no.history.hint": "メディア詳細を開くと、最近閲覧したコンテンツがここに保存されます。",
        "badge.favorite": "お気に入り",
        "badge.recent": "最近",
        // Navigation
        "nav.home": "ホーム",
        "nav.wallpaper": "壁纸",
        "nav.anime": "アニメ",
        "nav.media": "メディア",
        "nav.myMedia": "マイメディア",
        "nav.messages": "メッセージ",
        // Status bar
        "statusbar.showWindow": "メインウィンドウを表示",
        "statusbar.pauseWallpaper": "動的壁纸を一時停止",
        "statusbar.resumeWallpaper": "動的壁纸を再開",
        "statusbar.muteWallpaper": "動的壁纸をミュート",
        "statusbar.unmuteWallpaper": "ミュートを解除",
        "statusbar.enableWallpaper": "動的壁紙を有効にする",
        "statusbar.disableWallpaper": "動的壁紙を無効にする",
        "statusbar.quit": "終了",
        // Tabs
        "tab.all": "すべて",
        "tab.nature": "自然",
        "tab.technology": "テクノロジー",
        // Player
        "player.nowPlaying": "再生中",
        "player.selectWallpaper": "壁纸を選択",
        "player.playlist": "プレイリスト",
        "player.music": "音楽",
        "player.previous": "前へ",
        "player.play": "再生",
        "player.pause": "一時停止",
        "player.next": "次へ",
        "player.speed": "速度",
        "player.favorite": "お気に入り",
        "player.unfavorite": "お気に入り解除",
        // Loading
        "loading": "読み込み中...",
        "noData": "データなし",
        "loadMore": "もっと読み込む",
        // Errors
        "loadFailed": "読み込み失敗",
        "retry": "再試行",
        // Filters
        "contentLevel": "コンテンツレベル",
        "colorFilter": "色フィルター",
        "currentFilters": "現在のフィルター",
        "allRatios": "すべての比率",
        // Actions
        "wallpaperCount": "枚の壁纸",
        "exploreWallpaper": "壁纸を探索",
        "wallpaperLibrary": "壁纸ライブラリを探索",
        "discoverQuality": "デスクトップ用に厳選された高品質な壁纸を発見",
        "hotWallpaper": "人気",
        "exploreMedia": "動的メディアライブラリを探索",
        "hotDynamic": "人気の動的壁纸",
        "latestWallpaper": "最新の壁纸",
        "viewWallpaper": "壁纸を表示",
        // Detail
        "info": "情報",
        "specs": "仕様",
        "wallpaperColors": "色",
        "setWallpaper": "壁纸に設定",
        "wallpaperContent": "壁纸コンテンツ",
        "shareWallpaper": "壁纸を共有",
        "shareWithEveryone": "所有人とこの壁纸を共有",
        "generateShareable": "共有可能なリンクを生成",
        "sendToFriends": "友達と共有",
        "author": "作者:",
        "size": "サイズ:",
        "likes": "お気に入り:",
        "settingWallpaper": "デスクトップ壁纸を設定中...",
        "downloadingWallpaper": "オリジナルをダウンロード中...",
        "savedToDownloads": "ダウンロードフォルダに保存済み",
        // Filter view
        "apiKeyRequired": "API Keyが必要",
        "apiKeyNeeded": "SketchyとNSFWフィルターにはWallhaven API Keyが必要です。設定で構成してください。",
        "sketchyNsfwRequire": "Sketchy / NSFWにはまず設定でAPI Keyが必要です。",
        "filters.title": "フィルター",
        // Settings
        "settings.title": "設定",
        "preferences": "環境設定",
        "general.desc": "言語、API権限、キャッシュスペースを管理。",
        "download.desc": "自動ダウンロード戦略を制御し、現在のタスク状態を表示。",
        "scheduler.desc": "壁纸ローテーションのリズム、順序、ソースを設定。",
        "about.desc": "バージョン情報、プロジェクトの背景、外部リンクを表示。",
        "download": "ダウンロード",
        "scheduler": "自動切り替え",
        "languageSettings": "言語設定",
        "languageSettingsDesc": "アプリ全体で使用する表示言語を選択します。",
        "displayLanguage": "表示言語",
        "languageImmediateApply": "変更は現在の画面にすぐ反映されます。",
        "apiAccess": "APIアクセス",
        "apiAccessDesc": "Wallhaven API Keyを構成すると制限付きコンテンツにアクセス可能。",
        "getApiKey": "API Keyを取得",
        "apiNotConfigured": "未構成",
        "apiConfigured": "構成済み",
        "afterConfig": "構成後、制限付きコンテンツの閲覧と高頻度リクエストがすぐに有効になります。",
        "appearanceSettings": "外観設定",
        "appearanceSettingsDesc": "映画風の颗粒テクスチャオーバーレイなど、視覚効果をカスタマイズします。",
        "grainTextureEffect": "颗粒テクスチャ",
        "grainTextureEffectDesc": "すべてのページにフィルム颗粒テクスチャを適用し、映画のような質感を演出します。",
        // Content Types
        "content.wallpaper": "壁纸",
        "content.anime": "アニメ",
        "content.video": "動画",
        "content.wallpapers": "壁纸",
        "content.animes": "アニメ",
        "content.videos": "動画",
        "tab.wallpaper": "壁纸",
        "tab.anime": "アニメ",
        "tab.video": "動画",
        "library.wallpapers": "私の壁纸",
        "library.anime": "私のアニメ",
        "library.videos": "私の動画",
        "library.all": "すべてのお気に入り",
        "favorites.wallpaper": "壁纸のお気に入り",
        "favorites.anime": "アニメのお気に入り",
        "favorites.video": "動画のお気に入り",
        "downloads.wallpaper": "ダウンロードした壁纸",
        "downloads.anime": "ダウンロードしたアニメ",
        "downloads.video": "ダウンロードした動画",
        "watch.history": "視聴履歴",
        "watch.continue": "続きを見る",
        "episode": "第{number}話",
        "episodes": "エピソード",
        "total.episodes": "全{count}話",
        "current.episode": "第{number}話まで視聴",
        // Anime Detail
        "anime.watch": "視聴",
        "anime.continueWatch": "続きを見る",
        "anime.summary": "あらすじ",
        "anime.info": "情報",
        "anime.airDate": "放送開始",
        "anime.airWeekday": "更新曜日",
        "anime.type": "タイプ",
        "anime.rating": "評価",
        "anime.rank": "ランキング",
        "anime.type.tv": "TVアニメ",
        "anime.type.movie": "映画",
        "anime.type.ova": "OVA",
        "source.rules": "ソースルール",
        "source.rules.desc": "コンテンツソースの解析ルールを管理。URLまたはGitHubからインポートできます。",
        "install.rule": "ルールをインストール",
        "install.from.url": "URLからインストール",
        "install.from.github": "GitHubからインストール",
        "rule.url.placeholder": "https://example.com/rule.json",
        "github.owner": "リポジトリ所有者",
        "github.repo": "リポジトリ名",
        "github.path": "ファイルパス",
        "github.branch": "ブランチ",
        "dataSourceProfiles": "データソース設定",
        "dataSourceProfilesDesc": "壁紙とメディアのエンドポイント設定をインポート、切り替え、または初期化します。",
        "activeProfile": "現在のプロファイル",
        "importProfile": "JSONを読み込む",
        "importFromURL": "URLからインポート",
        "testProfile": "設定をテスト",
        "resetProfile": "デフォルトに戻す",
        "newProfile": "新規プロファイル",
        "openConfigDocs": "ドキュメントを開く",
        "cacheManagement": "キャッシュ管理",
        "cacheManagementDesc": "現在のキャッシュ使用量を表示し、必要に応じて素早くクリア。",
        "cacheUsed": "使用中のキャッシュ",
        "thumbnailsTemp": "サムネイルと一時ファイルの合計",
        "clearWhenLarge": "キャッシュ使用量が増え続ける場合はクリアして再生成できます。",
        "downloadPrefs": "ダウンロード設定",
        "downloadPrefsDesc": "閲覧中の自動ダウンロード戦略とローカル保存方法を定義。",
        "autoDownloadOriginal": "オリジナルを自動ダウンロード",
        "autoDownloadDesc": "閲覧中にHDオリジナルを自動キャッシュして次回の待ち時間を短縮。",
        "saveToDownloadsFolder": "ダウンロードフォルダに保存",
        "saveToDownloadsDesc": "ダウンロードした壁纸はシステムダウンロードにも保存され、整理が簡単。",
        "downloadTasks": "ダウンロードタスク",
        "downloadTasksDesc": "最近のダウンロード状態を表示し、現在のキューを素早く確認。",
        "noDownloadTasks": "ダウンロードタスクなし",
        "downloadTasksHint": "壁纸のダウンロードを開始すると進捗がここに表示されます。",
        "autoReplace": "自動切り替え",
        "autoReplaceDesc": "有効にすると、設定したリズムでデスクトップ壁纸が自動的にローテート。",
        "enableAutoReplace": "自動切り替えを有効にする",
        "currentlyRunning": "現在実行中で、壁纸は自動的に更新されます。",
        "currentlyStopped": "停止中は自動切り替えしません、手動で壁纸を設定できます。",
        "running": "実行中",
        "stopped": "停止済み",
        "recentChange": "最近の切り替え",
        "replaceRhythm": "切り替えリズム",
        "replaceRhythmDesc": "ローテーション間隔、再生順序、壁纸ソースを設定。",
        "replaceInterval": "切り替え間隔",
        "intervalDesc": "自動切り替えの頻度を決定。",
        "interval": "間隔",
        "replaceOrder": "切り替え順序",
        "sequential": "順序",
        "wallpaperSource": "壁纸ソース",
        "online": "オンライン",
        "local": "ローカル",
        "versionInfo": "バージョン",
        "elegantApp": "洗練されたmacOS壁纸ブラウザ",
        "projectInfo": "プロジェクト情報",
        "projectInfoDesc": "アプリの起源と技術スタックを素早く確認。",
        "dataSource": "データソース",
        "techStack": "技術スタック",
        "externalLinks": "外部リンク",
        "externalLinksDesc": "公式サイトにアクセスまたはフィードバック入口へ。",
        "visitWebsite": "ウェブサイト訪問",
        "visitWebsiteDesc": "wallhaven.ccの公式ギャラリーを閲覧。",
        "reportProblem": "問題を報告",
        "reportProblemDesc": "バグ提案または製品フィードバックを送信。",
        "minutes": "分",
        "hour": "時間",
        "hours": "時間",
        // Status
        "status.pending": "待機中",
        "status.downloading": "ダウンロード中",
        "status.paused": "一時停止",
        "status.completed": "完了",
        "status.failed": "失敗",
        "status.cancelled": "キャンセル済み",
        // Media detail
        "source": "ソース",
        "specs2": "仕様",
        "duration": "長さ",
        "download2": "ダウンロード",
        "title": "タイトル",
        "page": "ページ",
        "resolution2": "解像度",
        "format2": "フォーマット",
        "audio2": "オーディオ",
        "muted": "デフォルトミュート",
        "audioOn": "オン",
        "noDownloadOptions": "なし",
        "downloadSources": "ダウンロードソース",
        "applyingWallpaper": "mp4動的壁纸を適用中...",
        "downloadingMedia": "動的メディアリソースをダウンロード中...",
        // Editor
        "edit": "編集",
        "done": "完了",
        "selectAll": "すべて選択",
        "deselectAll": "選択解除",
        "selected": "選択済み",
        "delete": "削除",
        // Sort
        "sort.hot": "人気",
        "sort.latest": "最新",
        "sort.views": "閲覧数",
        "sort.likes": "お気に入り数",
        "sort.toplist": "ランキング",
        "sort.random": "ランダム",
        "sort.relevance": "関連性",
        "sort.newest": "最新",
        "sort.title2": "タイトル",
        "sort.format2": "仕様",
        "sortByNewest": "最新読み込み順",
        "sortByTitle": "タイトル順",
        "sortByFormat": "仕様順",
        // Purity
        "purity.sfw": "セーフコンテンツ",
        "purity.sketchy": "軽度の敏感",
        "purity.nsfw": "大人向けコンテンツ",
        // Aspect ratios
        "aspect.ultrawide": "ウルトラワイド",
        "aspect.dynamic": "動的",
        "aspect.loop": "ループ",
        "aspect.aesthetic": "エステティック",
        // Media type
        "media.count": "件のメディア",
        "media.loaded": "読み込み済み",
        "ascending2": "昇順",
        "descending2": "降順",
        // Media categories
        "filter.hd": "HD",
        "filter.game": "ゲーム",
        "filter.rain": "雨",
        "filter.cyberpunk": "サイバーパンク",
        "filter.nature2": "自然",
        "filter.dark": "ダーク",
        "filter.games": "ゲーム",
        "filter.superhero": "スーパーロ英雄",
        "filter.car": "車",
        "filter.tv": "テレビ",
        "filter.fantasy": "ファンタジー",
        "filter.space": "宇宙",
        "filter.technology2": "テクノロジー",
        "filter.holiday": "祝日",
        "filter.animal": "動物",
        "filter.horror": "ホラー",
        "filter.football": "サッカー",
        "filter.japan": "日本",
        // Empty states
        "noMediaFilter": "現在のフィルターにメディアがありません",
        "tryDifferentFilter": "別のカテゴリー、タグ、検索語で再試行してください。",
        "noMoreResults": "これ以上の結果はありません",
        "allLoaded": "読み込み済み",
        "mediaUnavailable": "メディアが一時的に利用できません",
        // Additional
        "noMessages": "メッセージはまだありません",
        "unknown": "不明",
        "created": "作成日",
        "ratio": "比率",
        "fileType": "タイプ",
        "shareLinkDescription": "リンクを持つ人は誰でもブラウザで同じWallhavenリソースを開いたり、ローカルに保存したりできます。",
        "videoMutedPlaying": "背景動画がミュートでループ再生中",
        "videoPlaying": "背景動画がループ再生中",
        "versions": "バージョン",
        // Settings additional
        "clearCacheConfirm": "すべてのキャッシュをクリアしてもよろしいですか？これによりダウンロードされたサムネイルと一時ファイルが削除されます。",
        "networkProxy": "ネットワークプロキシ",
        "networkProxyDesc": "中国のユーザーは自己ホスト型のCloudflare Workerを通じてWallHavenにアクセスできます。",
        "customWorkerUrl": "カスタム Worker URL",
        "notConfiguredDirect": "未構成（直接接続）",
        "deploymentGuide": "デプロイメントガイド",
        "afterWorkerConfig": "入力すると、WallHavenリクエストはWorkerプロキシを優先し、VPNなしでアクセスできます。",
        "mediaError": "メディアエラー",
        "searchWallpaper": "壁纸を検索...",
        // Profile Editor
        "editProfile": "プロファイル編集",
        "save": "保存",
        "pleaseFixErrors": "検証エラーを修正してください",
        "basicInfo": "基本情報",
        "basicInfoDesc": "プロファイルの識別と説明。",
        "profileID": "プロファイル ID",
        "profileName": "プロファイル名",
        "profileNamePlaceholder": "マイカスタムプロファイル",
        "profileDescription": "説明",
        "profileDescriptionPlaceholder": "このプロファイルのオプション説明",
        "wallpaperConfig": "壁紙設定",
        "wallpaperConfigDesc": "壁紙用のAPIエンドポイントとURLテンプレート。",
        "provider": "プロバイダー",
        "displayName": "表示名",
        "apiBaseURL": "API ベース URL",
        "searchPath": "検索パス",
        "wallpaperPath": "壁紙パス",
        "wallpaperPathHelp": "壁紙IDには {id} を使用",
        "imageURLTemplate": "画像URLテンプレート",
        "imageURLTemplateHelp": "プレースホルダーとして {prefix}、{id}、{ext} を使用",
        "authHeaderName": "認証ヘッダー名",
        "mediaConfig": "メディア設定",
        "mediaConfigDesc": "メディアソースの基本設定。",
        "baseURL": "ベース URL",
        "headers": "ヘッダー",
        "headersDesc": "メディアリクエストで送信されるHTTPヘッダー。",
        "headerKey": "キー",
        "headerValue": "値",
        "addHeader": "ヘッダーを追加",
        "routes": "ルート",
        "routesDesc": "異なるメディアページのURLパターン。",
        "routeHome": "ホーム",
        "routeMobile": "モバイル",
        "routeTag": "タグ",
        "routeTagHelp": "タグ識別子には {slug} を使用",
        "routeSearch": "検索",
        "routeSearchHelp": "検索語には {query} を使用",
        "routeDetail": "詳細",
        "routeDetailHelp": "項目識別子には {slug} を使用",
        "parsing": "パーシング",
        "parsingDesc": "メディアデータを抽出する正規表現パターン。",
        "listItemPatterns": "リスト項目パターン",
        "listItemPatternsDesc": "リストページから項目を抽出するパターン",
        "nextPagePatterns": "次ページパターン",
        "nextPagePatternsDesc": "次ページURLを見つけるパターン",
        "addPattern": "パターン追加",
        "tagPattern": "タグパターン",
        "tagPatternPlaceholder": "タグを抽出するパターン...",
        "downloadPattern": "ダウンロードパターン",
        "downloadPatternPlaceholder": "ダウンロードリンクを抽出するパターン...",
        "durationPattern": "再生時間パターン",
        "durationPatternPlaceholder": "動画再生時間を抽出するパターン...",
        // Network & Error States
        "error.network.title": "接続エラー",
        "error.network.message": "サーバーに接続できません。ネットワーク接続を確認して再試行してください。",
        "error.empty.title": "コンテンツなし",
        "error.empty.message": "現在のフィルターで項目が見つかりません。検索やフィルターを調整してみてください。",
        "error.server.title": "サーバーエラー",
        "error.server.message": "サーバーでエラーが発生しました。後でもう一度お試しください。",
        "error.offline.title": "オフライン",
        "error.offline.message": "オフライン状態のようです。ネットワーク接続を確認してください。",
        "error.unknown.title": "エラーが発生しました",
        "error.unknown.message": "予期しないエラーが発生しました。もう一度お試しください。",
        "tap.to.retry": "タップして再試行",
        "network.wifi": "WiFi",
        "network.cellular": "モバイルデータ",
        "network.connected": "接続済み",
        "network.offline": "オフライン",
        "weak.network.message": "ネットワーク接続が弱いです。コンテンツの読み込みが遅くなる場合があります。",
        "offline.title": "オフライン中",
        "offline.message": "接続を確認して再試行してください。キャッシュされたコンテンツは引き続き利用可能です。",
        // Settings - Update Check
        "apiKey": "API Key",
        "ruleRepository": "ルールリポジトリ",
        "ruleRepositoryDesc": "GitHubリポジトリURLを設定して、壁紙・メディア・アニメルールを自動同期。",
        "configured": "設定済み",
        "checkForUpdates": "アップデートを確認",
        "downloadUpdate": "アップデートをダウンロード",
        "newVersionAvailable": "新しいバージョンが利用可能",
        "goToDownload": "ダウンロードへ進む",
        "alreadyLatestVersion": "最新バージョンを使用中です",
        "newVersionFound": "新しいバージョンが見つかりました:",
        "goToDownloadQuestion": "ダウンロードページに移動しますか？"
    ]
]

// MARK: - 本地化字符串获取
func t(_ key: String) -> String {
    LocalizationService.shared.t(key)
}

// MARK: - View Extensions
extension View {
    func localized(_ key: String) -> some View {
        Text(t(key))
    }
}
